category: fixed
summary: "pipeline configuration no longer suppresses ``TypeError``"
description: |
  The configuration processing previously decided between two paths depending
  on whether some operation raised a ``TypeError``. This erroneously silenced
  any unrelated ``TypeError`` from misconfigurations.
pull requests:
- 91
