version: 2

build:
  image: "latest"

python:
  version: 3
  os: "ubuntu-22.04"
  install:
    - method: "pip"
      path: .
      extra_requirements:
        - "docs"

sphinx:
  builder: "html"
  configuration: "docs/conf.py"
