[pytest]
timeout = 15
filterwarnings =
    error
    ignore::DeprecationWarning:cobald.daemon.config.python
    ignore:'runtime.execute' is deprecated, directly use .*:DeprecationWarning
    ignore:'trio' services are deprecated, please use 'asyncio' for .*:DeprecationWarning
    ignore:'MetaRunner' is deprecated, directly use the concurrency frameworks:DeprecationWarning
    ignore:'AsyncioRunner' is deprecated, directly use 'asyncio':DeprecationWarning
    ignore:'TrioRunner' is deprecated, directly use 'asyncio' instead:DeprecationWarning
    ignore:'ThreadRunner' is deprecated, directly use 'threading':DeprecationWarning
