name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy-3.8', 'pypy-3.9']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[contrib]
    - name: Test with pytest
      run: |
        pytest -v --cov
      timeout-minutes: 5
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
